---
title: "lab7"
---

# Трансляция конференции с Positive Hack Days "Инструменты анализа блокчейна"

## План действий

-   Алгоритм консенсуса
-   TPS
-   Market data
-   Смартаконтракты
-   NFT

### Алгоритм консенсуса

Алгоритм консенсуса блокчейна - это совокупность принципов и правил, благодаря которым все участвующие в сети узлы (ноды) автоматически приходят к консенсусу о текущем состоянии сети. Таким образом гарантируется безопасность сети, то есть достоверность всех хранящихся в ней данных.

### TPS

ТРS - Transaction Per Second, количество
транзакций в секунду. Показывает, как быстро
обрабатываются переводы сетью блокчейна

### Matket data (Инструменты для анализа рынка)

#### Total supply

TS - общее предложение. TS = Кол-во создаваемых монет - токены что были сожжены

#### Circulation supply

CS - количество монет, которые открыты для торгов (не заблокированы)

#### Market Cap

MC - рыночная капитализация. MC = текущая цена * циркулирующее предложение

#### Fully Diluted Valuation

FDV - полностью разбавленная оценочная стоимость. Теоретически цена всех монет, если в обращении max/total supply

### Смартконтракты

Это код, который находится в сети блокчейн. Он исполняется при выполнении
определенных условий, и может делать
практически что угодно в блокчейне.

Не все блокчейны нативно поддерживают возможность создания смартконтрактов. Пример - Bitcoin.

### NFT 

NFT – это невзаимозаменяемый токен (non-fungible token). Невзаимозаменяемость означает уникальность и невозможность замены одного объекта на другой. В отличие от NFT, физические деньги и криптовалюты взаимозаменяемы — одно можно обменять на другое. Каждый NFT содержит цифровую подпись, которая делает токен уникальным.
